- name: Creates App directory
  shell: |
    mkdir -p ~/app

- name: copying zipped artifact
  copy:
    src: ../../artifact.tar.gz
    dest: ~/app

- name: Install dependencies
  shell: |
    cd /home/ubuntu/app
    tar xf /home/ubuntu/app/artifact.tar.gz

- name: Start the app
  shell: |
    cd /home/ubuntu/app  
    npm install
    pm2 stop default  
    pm2 start npm -- start
    sleep 20
    echo "Done."